### ISSUE TITLE
Address security considerations related to dependencies

### ISSUE THREAD

**Issue by vielmetti** [packethost/ui-driver-packet#5]
The `dependabot` system has alerted to potential issues with several dependencies in this package, with PR's open #2 #3 #4 to bring the dependencies up to date.

**Comment by vielmetti** [comment]
@alibazlamit - I think the `dependabot` alerts regarding security considerations might be easy to resolve, given that the changes appear to be small enough to be point fixes and not major releases.

**Comment by alibazlamit** [comment]
@vielmetti Thanks for the heads up. Resolved all security issues.
